apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-con
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Shalom from the Kubernetes cluster"
          restartPolicy: OnFailure
