apiVersion: batch/v1
kind: CronJob
metadata:
  name: concurrency-cronjob
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 600
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-con
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo Hello; sleep 90; echo Shalom
          restartPolicy: OnFailure

