apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  template:
    metadata:
      name: nginx-daemonset
      labels:
        app: nginx-daemonset
    spec:
      containers:
      - name: nginx-daemonset
        image: nginx
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: nginx-daemonset
