apiVersion: v1
kind: Pod
metadata:
  name: pod-main
  labels:
    category: main
spec:
  containers:
  - name: container
    image: jesuswithme/messtige-home
---
apiVersion: v1
kind: Service
metadata:
  name: main-svc
spec:
  selector:
    category: main
  ports:
  - port: 80
