apiVersion: v1
kind: Pod
metadata:
  name: pod-order
  labels:
    category: order
spec:
  containers:
  - name: container
    image: jesuswithme/messtige-order
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    category: order
  ports:
  - port: 80
