apiVersion: v1
kind: Pod
metadata: 
  name: mypod-livenessprobe
spec: 
  containers: 
  - image: nginx:1.14
    name: nginx
    ports: 
    - containerPort: 80
      protocol: TCP
    livenessProbe: 
      httpGet: 
        path: /
        port: 80

      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 1      
