apiVersion: v1
kind: Pod
metadata:
  name: pod-label
  labels:
    app: nginx
    environment: production
spec:
  containers:
  - name: nginx-con
    image: nginx:1.14
    ports:
    - containerPort: 80
