apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mypod
  name: mypod-annotation
  annotations: 
    builder: "Yongshik Lee"
spec:
  containers:
  - image: nginx:1.14
    name: mypod-con
    ports: 
    - containerPort: 80  
