apiVersion: v1
kind: PersistentVolume      
metadata:
  name: jesuswithme-pv-hostpah
  labels:
    storage: jesuswithme-pv-test
spec:
  capacity:             
    storage: 5Gi
  accessModes: 
  - ReadWriteOnce
  volumeMode: Filesystem  
  storageClassName: jesuswithme-storage  
  persistentVolumeReclaimPolicy: Delete 
                   
  hostPath: 
    path: /k8s-volume

