apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jesuswithme-pvc-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:          
    requests:
      storage: 1Gi                                          
  storageClassName: jesuswithme-storage
  selector:             
    matchLabels:    
      storage: jesuswithme-pv-test
