apiVersion: v1
kind: Pod
metadata: 
  name: randomid-volume
spec: 
  containers: 
  - image: jesuswithme/randomid:env
    env:
    - name: INTERVAL
      valueFrom: 
        configMapKeyRef: 
          name: nginx-config
          key: INTERVAL
    name: fakeid
    volumeMounts: 
    - name: html
      mountPath: /wwwdata
  - image: nginx:1.14
    name: web-server
    ports: 
    - containerPort: 80
    volumeMounts: 
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
  volumes: 
  - name: html
    emptyDir: {}
  - name: config
    configMap: 
      name: nginx-config
      items: 
      - key: nginx-config.conf
        path: nginx-config.conf
