apiVersion: v1
kind: Pod
metadata: 
  name: randomid-volume-secret
spec: 
  containers: 
  - image: jesuswithme/randomid:env
    env:
    - name: INTERVAL
      valueFrom: 
        secretKeyRef: 
          name: nginx-secret
          key: INTERVAL
    name: fakeid-generator
    volumeMounts: 
    - name: html
      mountPath: /wwwdata
  - image: nginx:1.14
    name: web-server
    ports: 
    - containerPort: 80
    volumeMounts: 
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
  volumes: 
  - name: html
    emptyDir: {}
  - name: config
    secret: 
      secretName: nginx-secret
      items: 
      - key: nginx-config.conf
        path: nginx-config.conf
