apiVersion: v1
kind: Pod
metadata: 
  name: randomid-env-secret
spec: 
  containers: 
  - image: jesuswithme/randomid:env
    env:
    - name: INTERVAL
      valueFrom: 
        secretKeyRef: 
          name: nginx-secret
          key: INTERVAL
    name: fakeid-generator
    volumeMounts: 
    - name: html
      mountPath: /wwwdata
  - image: nginx:1.14
    name: web-server
    volumeMounts: 
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports: 
      - containerPort: 80
  volumes: 
    - name: html
      emptyDir: {}
